In [1]:
%load_ext autoreload
%autoreload 2

import sys, os
sys.path.append("../")
from iotools import readgtf
from iotools.readOxford import ReadOxford
from collections import defaultdict

gtfpath = "/cbscratch/franco/datasets/gtex/gencode.v19.annotation.gtf.gz"
gene_info = readgtf.gencode_v12(gtfpath, trim=False)


In [2]:

chrom = 6
oxf_file = "/cbscratch/franco/datasets/gtex/GTEx_450Indiv_genot_imput_info04_maf01_HWEp1E6_dbSNP135IDs_donorIDs_dosage_chr{:d}.gz".format(chrom)
# outfile  = "/cbscratch/franco/datasets/gtex/prefiltered/GTEx_450Indiv_filtered_chr{:d}.gz".format(chrom)
fam_file = "/cbscratch/franco/datasets/gtex/donor_ids.fam"

oxf = ReadOxford(oxf_file, fam_file, isdosage=True) #should be self.args.isdosage and self.args.oxf_columns
dosage = oxf.dosage
gt_donor_ids = oxf.samplenames
snpinfo = oxf.snpinfo

2018-08-30 16:48:00,963 | iotools.readOxford | INFO | Started reading genotype.
2018-08-30 16:50:32,336 | iotools.readOxford | INFO | Completed reading 768209 SNPs of 450 samples.


In [50]:
snpinfo[0]

SnpInfo(chrom=6, varid='rs28546785', bp_pos=89949, ref_allele='G', alt_allele='A', maf=0.5452288888888885)

In [39]:
chrom   = snpinfo[0].chrom
window  = 1e6
w_start = pos - window
w_end   = pos + window

chr_genes = list()
chr_ix_genes = list()
for i,g in enumerate(gene_info):
    if g.chrom == chrom:
        chr_genes.append(g)
        chr_ix_genes.append(i)
chr_ix_genes = np.array(chr_ix_genes)

In [40]:
print(chr_genes[:3])
print(chr_ix_genes[:3])

[GeneInfo(name='DUSP22', ensembl_id='ENSG00000112679.10', chrom=6, start=291629, end=351355), GeneInfo(name='IRF4', ensembl_id='ENSG00000137265.10', chrom=6, start=391738, end=411447), GeneInfo(name='EXOC2', ensembl_id='ENSG00000112685.9', chrom=6, start=485133, end=693116)]
[6095 6096 6097]


In [59]:
import time

start_time = time.time()
cis_masks = list()
prev_start = 0
window  = 1e6

for s in snpinfo:
    #here starts for each snp
    pos     = s.bp_pos
    w_start = pos - window
    w_end   = pos + window
    cis_genes_ix = list()
    for i, g in enumerate(chr_genes[prev_start:]):
        if g.start >= w_start and g.start <= w_end:
            # cis_genes_ix.append([prev_start + i, g])
            cis_genes_ix.append(prev_start + i)
        elif g.end >= w_start and g.end <= w_end:
            # cis_genes_ix.append([prev_start + i, g])
            cis_genes_ix.append(prev_start + i)
        if g.start > w_end:
            break
    cis_genes_ix = np.array(cis_genes_ix)
    if len(cis_genes_ix) > 0:
        gx_matrix_ix = chr_ix_genes[cis_genes_ix]
        # prev_start = cis_genes_ix[0][0]
        if len(gx_matrix_ix) != len(cis_genes_ix):
            print("LPM")
            raise
        if prev_start != cis_genes_ix[0]:
            prev_start = cis_genes_ix[0]
    else:
        print(pos, "empty cis")
        gx_matrix_ix = np.array([])
    cis_masks.append(gx_matrix_ix)

print("--- %s seconds ---" % (time.time() - start_time))


58513965 empty cis
58514351 empty cis
58514471 empty cis
58514557 empty cis
58514559 empty cis
58514717 empty cis
58514720 empty cis
58514721 empty cis
58514818 empty cis
58515124 empty cis
58515747 empty cis
58515814 empty cis
58515815 empty cis
58516307 empty cis
58516383 empty cis
58516551 empty cis
58516625 empty cis
58516652 empty cis
58516838 empty cis
58516928 empty cis
58516946 empty cis
58516978 empty cis
58517042 empty cis
58517054 empty cis
58517164 empty cis
58517189 empty cis
58517202 empty cis
58517268 empty cis
58517298 empty cis
58517486 empty cis
58517505 empty cis
58517721 empty cis
58517724 empty cis
58517990 empty cis
58518171 empty cis
58518789 empty cis
58518983 empty cis
58519085 empty cis
58519123 empty cis
58519218 empty cis
58519221 empty cis
58519607 empty cis
58519610 empty cis
58519916 empty cis
58520122 empty cis
58520362 empty cis
58520397 empty cis
58520401 empty cis
58520422 empty cis
58520572 empty cis
58520731 empty cis
58521133 empty cis
58521313 emp

58680934 empty cis
58681499 empty cis
58681923 empty cis
58681971 empty cis
58681978 empty cis
58682443 empty cis
58682673 empty cis
58683176 empty cis
58683323 empty cis
58683455 empty cis
58683792 empty cis
58684094 empty cis
58684223 empty cis
58684372 empty cis
58684393 empty cis
58684404 empty cis
58684440 empty cis
58685908 empty cis
58686051 empty cis
58686356 empty cis
58686427 empty cis
58686480 empty cis
58686777 empty cis
58687140 empty cis
58687167 empty cis
58687700 empty cis
58687787 empty cis
58687841 empty cis
58687850 empty cis
58687945 empty cis
58688229 empty cis
58688469 empty cis
58688556 empty cis
58689129 empty cis
58689562 empty cis
58689740 empty cis
58689835 empty cis
58690091 empty cis
58690514 empty cis
58690523 empty cis
58690609 empty cis
58690737 empty cis
58691074 empty cis
58691405 empty cis
58691668 empty cis
58692034 empty cis
58692101 empty cis
58692330 empty cis
58692389 empty cis
58692486 empty cis
58692773 empty cis
58693064 empty cis
58693325 emp

67417475 empty cis
67417793 empty cis
67417874 empty cis
67417944 empty cis
67418040 empty cis
67418280 empty cis
67418417 empty cis
67419032 empty cis
67419244 empty cis
67419300 empty cis
67419656 empty cis
67419709 empty cis
67420028 empty cis
67420711 empty cis
67420932 empty cis
67421078 empty cis
67421096 empty cis
67421384 empty cis
67421714 empty cis
67422006 empty cis
67422038 empty cis
67422184 empty cis
67422217 empty cis
67422285 empty cis
67422581 empty cis
67422593 empty cis
67423111 empty cis
67423356 empty cis
67423457 empty cis
67423474 empty cis
67423526 empty cis
67423765 empty cis
67423838 empty cis
67424205 empty cis
67424342 empty cis
67425233 empty cis
67425567 empty cis
67425796 empty cis
67425799 empty cis
67425904 empty cis
67426185 empty cis
67426208 empty cis
67426795 empty cis
67426975 empty cis
67427758 empty cis
67427783 empty cis
67427812 empty cis
67428031 empty cis
67428926 empty cis
67429031 empty cis
67429337 empty cis
67429550 empty cis
67429994 emp

67558297 empty cis
67558321 empty cis
67558481 empty cis
67558501 empty cis
67558513 empty cis
67558952 empty cis
67559115 empty cis
67559149 empty cis
67559323 empty cis
67559669 empty cis
67559743 empty cis
67559927 empty cis
67560147 empty cis
67560211 empty cis
67560353 empty cis
67560905 empty cis
67560972 empty cis
67561058 empty cis
67561239 empty cis
67561267 empty cis
67561353 empty cis
67561377 empty cis
67561414 empty cis
67561415 empty cis
67561566 empty cis
67561603 empty cis
67561610 empty cis
67561693 empty cis
67561739 empty cis
67561835 empty cis
67561904 empty cis
67561931 empty cis
67561944 empty cis
67562122 empty cis
67562265 empty cis
67562268 empty cis
67562340 empty cis
67562373 empty cis
67562403 empty cis
67562566 empty cis
67562937 empty cis
67563022 empty cis
67563438 empty cis
67563701 empty cis
67563742 empty cis
67563808 empty cis
67563828 empty cis
67564992 empty cis
67565476 empty cis
67565511 empty cis
67565880 empty cis
67565940 empty cis
67566248 emp

67716274 empty cis
67716381 empty cis
67716535 empty cis
67717049 empty cis
67717160 empty cis
67717251 empty cis
67717834 empty cis
67718019 empty cis
67719155 empty cis
67719498 empty cis
67719742 empty cis
67719757 empty cis
67719904 empty cis
67719994 empty cis
67720324 empty cis
67720416 empty cis
67720441 empty cis
67720985 empty cis
67721207 empty cis
67721226 empty cis
67721344 empty cis
67721488 empty cis
67722180 empty cis
67722409 empty cis
67722869 empty cis
67723184 empty cis
67723446 empty cis
67723968 empty cis
67723973 empty cis
67724162 empty cis
67724471 empty cis
67724614 empty cis
67724866 empty cis
67725291 empty cis
67725338 empty cis
67725578 empty cis
67725640 empty cis
67726176 empty cis
67726374 empty cis
67727005 empty cis
67727593 empty cis
67728006 empty cis
67728010 empty cis
67728226 empty cis
67728434 empty cis
67728523 empty cis
67728569 empty cis
67729127 empty cis
67729136 empty cis
67729156 empty cis
67729172 empty cis
67729305 empty cis
67729455 emp

67822919 empty cis
67823072 empty cis
67823168 empty cis
67823430 empty cis
67823468 empty cis
67823557 empty cis
67823616 empty cis
67823932 empty cis
67824155 empty cis
67824186 empty cis
67824316 empty cis
67824446 empty cis
67824712 empty cis
67824769 empty cis
67824872 empty cis
67824964 empty cis
67825111 empty cis
67825174 empty cis
67825362 empty cis
67825708 empty cis
67825740 empty cis
67825867 empty cis
67825890 empty cis
67826057 empty cis
67826171 empty cis
67826259 empty cis
67826463 empty cis
67826759 empty cis
67826760 empty cis
67826835 empty cis
67826887 empty cis
67826911 empty cis
67826962 empty cis
67827083 empty cis
67827084 empty cis
67827120 empty cis
67827201 empty cis
67827392 empty cis
67827619 empty cis
67827624 empty cis
67827737 empty cis
67827796 empty cis
67827894 empty cis
67827908 empty cis
67827932 empty cis
67827936 empty cis
67827946 empty cis
67827960 empty cis
67827964 empty cis
67827974 empty cis
67827979 empty cis
67828002 empty cis
67828007 emp

67942851 empty cis
67942878 empty cis
67942895 empty cis
67942896 empty cis
67942916 empty cis
67942918 empty cis
67942919 empty cis
67942964 empty cis
67942977 empty cis
67943025 empty cis
67943026 empty cis
67943078 empty cis
67943142 empty cis
67943185 empty cis
67943204 empty cis
67943211 empty cis
67943225 empty cis
67944078 empty cis
67944934 empty cis
67945009 empty cis
67945095 empty cis
67945512 empty cis
67945529 empty cis
67946206 empty cis
67947059 empty cis
67947566 empty cis
67947988 empty cis
67948458 empty cis
67948588 empty cis
67948758 empty cis
67948979 empty cis
67948982 empty cis
67949164 empty cis
67949265 empty cis
67949808 empty cis
67949869 empty cis
67950785 empty cis
67950825 empty cis
67950851 empty cis
67950984 empty cis
67951104 empty cis
67951164 empty cis
67951738 empty cis
67951941 empty cis
67952315 empty cis
67952574 empty cis
67952945 empty cis
67952979 empty cis
67953167 empty cis
67953414 empty cis
67953460 empty cis
67953671 empty cis
67953919 emp

68124148 empty cis
68124808 empty cis
68125086 empty cis
68125127 empty cis
68125205 empty cis
68125255 empty cis
68125755 empty cis
68125910 empty cis
68126223 empty cis
68126429 empty cis
68126462 empty cis
68126529 empty cis
68126607 empty cis
68126879 empty cis
68126975 empty cis
68127086 empty cis
68127190 empty cis
68127254 empty cis
68127773 empty cis
68128027 empty cis
68128097 empty cis
68128319 empty cis
68128385 empty cis
68128477 empty cis
68128591 empty cis
68128705 empty cis
68128752 empty cis
68129100 empty cis
68129110 empty cis
68129298 empty cis
68129628 empty cis
68129727 empty cis
68129771 empty cis
68129860 empty cis
68129992 empty cis
68130177 empty cis
68130213 empty cis
68130324 empty cis
68130423 empty cis
68130586 empty cis
68130615 empty cis
68130828 empty cis
68130941 empty cis
68130960 empty cis
68130972 empty cis
68131238 empty cis
68131291 empty cis
68131409 empty cis
68131895 empty cis
68131987 empty cis
68132209 empty cis
68132222 empty cis
68133163 emp

68317030 empty cis
68317204 empty cis
68317796 empty cis
68317826 empty cis
68318315 empty cis
68318559 empty cis
68318851 empty cis
68318857 empty cis
68319661 empty cis
68319694 empty cis
68319757 empty cis
68319802 empty cis
68320508 empty cis
68320950 empty cis
68321258 empty cis
68321286 empty cis
68322659 empty cis
68322711 empty cis
68322852 empty cis
68322864 empty cis
68323096 empty cis
68323245 empty cis
68323663 empty cis
68323922 empty cis
68323989 empty cis
68324240 empty cis
68324451 empty cis
68324473 empty cis
68324528 empty cis
68324549 empty cis
68324550 empty cis
68324696 empty cis
68324829 empty cis
68324925 empty cis
68325285 empty cis
68325344 empty cis
68325475 empty cis
68325975 empty cis
68325976 empty cis
68326045 empty cis
68326186 empty cis
68326288 empty cis
68326808 empty cis
68327019 empty cis
68327030 empty cis
68327127 empty cis
68327229 empty cis
68327726 empty cis
68327974 empty cis
68328235 empty cis
68328329 empty cis
68328401 empty cis
68328628 emp

92538716 empty cis
92538849 empty cis
92539077 empty cis
92539102 empty cis
92539213 empty cis
92540012 empty cis
92540459 empty cis
92540561 empty cis
92540853 empty cis
92541269 empty cis
92541643 empty cis
92541795 empty cis
92542496 empty cis
92542528 empty cis
92542727 empty cis
92543667 empty cis
92543963 empty cis
92544026 empty cis
92544400 empty cis
92544636 empty cis
92544703 empty cis
92544921 empty cis
92545131 empty cis
92545396 empty cis
92545905 empty cis
92546357 empty cis
92547148 empty cis
92547691 empty cis
92548359 empty cis
92548524 empty cis
92548542 empty cis
92548582 empty cis
92548665 empty cis
92548669 empty cis
92548671 empty cis
92548726 empty cis
92548874 empty cis
92548890 empty cis
92549186 empty cis
92549522 empty cis
92550258 empty cis
92550520 empty cis
92550712 empty cis
92550969 empty cis
92551369 empty cis
92552050 empty cis
92552200 empty cis
92552637 empty cis
92552749 empty cis
92552875 empty cis
92552990 empty cis
92553015 empty cis
92553255 emp

92741214 empty cis
92741318 empty cis
92741487 empty cis
92741786 empty cis
92741869 empty cis
92742333 empty cis
92742417 empty cis
92742714 empty cis
92742755 empty cis
92743082 empty cis
92743092 empty cis
92743118 empty cis
92743585 empty cis
92743644 empty cis
92743685 empty cis
92744042 empty cis
92744251 empty cis
92744380 empty cis
92744999 empty cis
92745020 empty cis
92745176 empty cis
92745415 empty cis
92746045 empty cis
92746054 empty cis
92746376 empty cis
92746538 empty cis
92746638 empty cis
92746910 empty cis
92747135 empty cis
92747643 empty cis
92747673 empty cis
92747744 empty cis
92748624 empty cis
92748677 empty cis
92748723 empty cis
92748731 empty cis
92748810 empty cis
92748943 empty cis
92749256 empty cis
92749464 empty cis
92749512 empty cis
92749573 empty cis
92749801 empty cis
92749910 empty cis
92749950 empty cis
92749974 empty cis
92750174 empty cis
92750321 empty cis
92750397 empty cis
92750417 empty cis
92750444 empty cis
92750490 empty cis
92750918 emp

92943943 empty cis
92944539 empty cis
92944806 empty cis
92944944 empty cis
92945531 empty cis
92945567 empty cis
92945826 empty cis
92945895 empty cis
92946046 empty cis
92946240 empty cis
92946413 empty cis
92946740 empty cis
92947092 empty cis
92947194 empty cis
92947310 empty cis
92947655 empty cis
92947755 empty cis
92948460 empty cis
92948728 empty cis
92948787 empty cis
92949038 empty cis
92949112 empty cis
92949293 empty cis
92949684 empty cis
103518105 empty cis
103518312 empty cis
103518732 empty cis
103518749 empty cis
103518819 empty cis
103518856 empty cis
103518951 empty cis
103519056 empty cis
103519201 empty cis
103519750 empty cis
103520409 empty cis
103520861 empty cis
103521211 empty cis
103521720 empty cis
103521799 empty cis
103521927 empty cis
103521968 empty cis
103522397 empty cis
103522655 empty cis
103522685 empty cis
103523007 empty cis
103523008 empty cis
103523620 empty cis
103524145 empty cis
103525004 empty cis
103525105 empty cis
103525670 empty cis
1035

103683936 empty cis
103684254 empty cis
103684528 empty cis
103684742 empty cis
103685179 empty cis
103685547 empty cis
103686622 empty cis
103686829 empty cis
103687314 empty cis
103687329 empty cis
103687833 empty cis
103687978 empty cis
103688289 empty cis
103688317 empty cis
103688365 empty cis
103688537 empty cis
103688589 empty cis
103688655 empty cis
103688678 empty cis
103689022 empty cis
103689085 empty cis
103689253 empty cis
103690245 empty cis
103690658 empty cis
103690786 empty cis
103691061 empty cis
103691201 empty cis
103691366 empty cis
103691567 empty cis
103691571 empty cis
103691621 empty cis
103691637 empty cis
103691752 empty cis
103692859 empty cis
103692908 empty cis
103692925 empty cis
103692937 empty cis
103693057 empty cis
103693059 empty cis
103693081 empty cis
103693332 empty cis
103693335 empty cis
103693452 empty cis
103693934 empty cis
103694491 empty cis
103694577 empty cis
103694606 empty cis
103695764 empty cis
103695972 empty cis
103696057 empty cis


103870611 empty cis
103870785 empty cis
103870895 empty cis
103871342 empty cis
103871412 empty cis
103871890 empty cis
103871954 empty cis
103871961 empty cis
103872066 empty cis
103872356 empty cis
103872413 empty cis
103872636 empty cis
103872719 empty cis
103873136 empty cis
103873242 empty cis
103874177 empty cis
103874204 empty cis
103874410 empty cis
103874413 empty cis
103874460 empty cis
103874464 empty cis
103874706 empty cis
103874859 empty cis
103875107 empty cis
103875566 empty cis
103875613 empty cis
103875654 empty cis
103875911 empty cis
103875945 empty cis
103876113 empty cis
103876161 empty cis
103876378 empty cis
103876717 empty cis
103877066 empty cis
103877383 empty cis
103877691 empty cis
103877992 empty cis
103878753 empty cis
103878759 empty cis
103879074 empty cis
103879297 empty cis
103879305 empty cis
103879453 empty cis
103879505 empty cis
103879537 empty cis
103879580 empty cis
103879846 empty cis
103879956 empty cis
103880531 empty cis
103881155 empty cis


104004272 empty cis
104004341 empty cis
104004347 empty cis
104004438 empty cis
104004447 empty cis
104004597 empty cis
104004814 empty cis
104004843 empty cis
104005406 empty cis
104005434 empty cis
104005549 empty cis
104006194 empty cis
104006258 empty cis
104006272 empty cis
104006360 empty cis
104006679 empty cis
104006807 empty cis
104006836 empty cis
104007137 empty cis
104007167 empty cis
104007334 empty cis
104007376 empty cis
104007511 empty cis
104007516 empty cis
104007581 empty cis
104007816 empty cis
104007856 empty cis
104007967 empty cis
104007994 empty cis
104008031 empty cis
104008085 empty cis
104008166 empty cis
104008356 empty cis
104008406 empty cis
104008666 empty cis
104008699 empty cis
104008799 empty cis
104009000 empty cis
104009076 empty cis
104009420 empty cis
104009446 empty cis
104010150 empty cis
104010191 empty cis
104010321 empty cis
104010330 empty cis
104010340 empty cis
104010457 empty cis
104010581 empty cis
104010588 empty cis
104010758 empty cis


104167045 empty cis
104168069 empty cis
104168081 empty cis
104168218 empty cis
104168273 empty cis
104168390 empty cis
104168425 empty cis
104168480 empty cis
104168548 empty cis
104169039 empty cis
104169338 empty cis
104169604 empty cis
104169702 empty cis
104169711 empty cis
104169741 empty cis
104169749 empty cis
104169764 empty cis
104169766 empty cis
104169768 empty cis
104170763 empty cis
104170801 empty cis
104170883 empty cis
104171415 empty cis
104171785 empty cis
104171930 empty cis
104172237 empty cis
104172238 empty cis
104172443 empty cis
104173631 empty cis
104173748 empty cis
104174389 empty cis
104175118 empty cis
104175613 empty cis
104175682 empty cis
104175811 empty cis
140696513 empty cis
140697541 empty cis
140697627 empty cis
140697640 empty cis
140697774 empty cis
140698018 empty cis
140698369 empty cis
140698568 empty cis
140700819 empty cis
140700867 empty cis
140701042 empty cis
140701396 empty cis
140701402 empty cis
140701423 empty cis
140701518 empty cis


141068983 empty cis
141069018 empty cis
141069030 empty cis
141070131 empty cis
141070619 empty cis
141070758 empty cis
141070761 empty cis
141070763 empty cis
141070886 empty cis
141070901 empty cis
141071382 empty cis
141071771 empty cis
141072156 empty cis
141072208 empty cis
141072401 empty cis
141072528 empty cis
141072564 empty cis
141072876 empty cis
141073365 empty cis
141074225 empty cis
141075645 empty cis
141075898 empty cis
141076567 empty cis
141076804 empty cis
141077493 empty cis
141077497 empty cis
141078779 empty cis
141079124 empty cis
141079534 empty cis
141079652 empty cis
141079658 empty cis
141079947 empty cis
141079950 empty cis
141080914 empty cis
141081275 empty cis
141081277 empty cis
141081622 empty cis
141081623 empty cis
141081736 empty cis
141081844 empty cis
141082306 empty cis
141082657 empty cis
141083234 empty cis
141083972 empty cis
141084084 empty cis
141085396 empty cis
141086111 empty cis
141086802 empty cis
141086836 empty cis
141086917 empty cis


141289530 empty cis
141289614 empty cis
141289655 empty cis
141289922 empty cis
141290047 empty cis
141290210 empty cis
141290826 empty cis
141291135 empty cis
141291169 empty cis
141291199 empty cis
141291504 empty cis
141292318 empty cis
141292365 empty cis
141293246 empty cis
141293450 empty cis
141293504 empty cis
141293889 empty cis
141293952 empty cis
141294469 empty cis
141294484 empty cis
141294518 empty cis
141294957 empty cis
141295186 empty cis
141295231 empty cis
141295397 empty cis
141296097 empty cis
141296597 empty cis
141296842 empty cis
141297381 empty cis
141297999 empty cis
141299602 empty cis
141299694 empty cis
141299725 empty cis
141299898 empty cis
141299899 empty cis
141300184 empty cis
141300562 empty cis
141300980 empty cis
141301055 empty cis
141301076 empty cis
141301098 empty cis
141301409 empty cis
141301526 empty cis
141301609 empty cis
141301761 empty cis
141302171 empty cis
141302530 empty cis
141302593 empty cis
141302656 empty cis
141302682 empty cis


In [26]:
print(len(cis_masks))

86486


In [57]:
len(np.array([]))

0

In [49]:
cis_masks[:10]

[array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099]),
 array([6095, 6096, 6097, 6098, 6099])]

In [151]:
from functools import wraps
import time

def timeit(f):
    @wraps(f)
    def wrap(*args, **kw):
        ts = time.time()
        result = f(*args, **kw)
        te = time.time()
        print('{:s} took: {:.6f} seconds'.format(f.__name__, te-ts))
        return result
    return wrap

In [162]:

@timeit
def get_cismasks(snpinfo, gene_info, chrom):
    # gene_info MUST be sorted as in the gene expression matrix
    # chrom   = snpinfo[0].chrom
    window  = 1e6

    chr_genes = list()
    chr_ix_genes = list()
    for i,g in enumerate(gene_info):
        if g.chrom == chrom:
            chr_genes.append(g)
            chr_ix_genes.append(i)
    chr_ix_genes = np.array(chr_ix_genes)
    
    cis_masks = list()
    prev_start = 0

    for s in snpinfo:
        #here starts for each snp
        pos     = s.bp_pos
        w_start = pos - window
        w_end   = pos + window
        cis_genes_ix = list()
        for i, g in enumerate(chr_genes[prev_start:]):
            if g.start >= w_start and g.start <= w_end:
                # cis_genes_ix.append([prev_start + i, g])
                cis_genes_ix.append(prev_start + i)
            elif g.end >= w_start and g.end <= w_end:
                # cis_genes_ix.append([prev_start + i, g])
                cis_genes_ix.append(prev_start + i)
            if g.start > w_end:
                break
        cis_genes_ix = np.array(cis_genes_ix)
        if len(cis_genes_ix) > 0:
            gx_matrix_ix = chr_ix_genes[cis_genes_ix]
            if len(gx_matrix_ix) != len(cis_genes_ix):
                raise
            if prev_start != cis_genes_ix[0]:
                prev_start = cis_genes_ix[0]
        else:
            # print(pos, "empty cis")
            gx_matrix_ix = np.array([])
        cis_masks.append(gx_matrix_ix)
    return cis_masks

In [163]:
import time

@timeit
def compress_cis_masks(cis_masks):
    snps_masks_lists = [] # contains lists of snp indices for each mask.
                          # i.e snps_masks_lists[0] is a list with all the snps 
                          # that have the same mask: compressed_masks[0]
    compressed_snps  = [] # temp list that will be used to build snps_masks_lists     
    compressed_masks = [] # contains all unique masks

    prev_mask = cis_masks[0]
    compressed_snps.append(0)
    for i in range(1, len(cis_masks)):
        # if masks are the same, add the snp index
        if (len(cis_masks[i]) == len(prev_mask)) and all(cis_masks[i] == prev_mask):
            compressed_snps.append(i)
        else:
            compressed_masks.append(cis_masks[i])
            prev_mask = cis_masks[i]
            snps_masks_lists.append(compressed_snps)
            compressed_snps = []
            compressed_snps.append(i)
    # add the last set of snps for the final mask
    snps_masks_lists.append(compressed_snps)
    compressed_masks.append(cis_masks[-1])
    return snps_masks_lists, compressed_masks


In [164]:
cis_masks = get_cismasks(snpinfo, gene_info, chrom)
snps_masks_lists, compressed_masks = compress_cis_masks(cis_masks)

get_cismasks took: 115.687452 seconds
compress_cis_masks took: 2.371817 seconds


In [165]:
snps_masks_lists, compressed_masks = compress_cis_masks(cis_masks)

compress_cis_masks took: 2.317392 seconds


In [166]:
print(len(compressed_masks), len(snps_masks_lists))

2059 2059


In [167]:
acum = 0
for e in snps_masks_lists:
    acum += len(e)
print("snps with mask: {:d}".format(acum))
print("total snps: {:d}".format(len(snpinfo)))

snps with mask: 768209
total snps: 768209


In [169]:
snp_batch = snps_masks_lists[0]
mask      = compressed_masks[0]

In [170]:
snp_batch

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [179]:
gx = np.ones((23000, 500))
print(gx.shape)
gx_crop = np.delete(gx, mask, axis=0)
print(gx_crop.shape)
print(gx.shape)

(23000, 500)
(22994, 500)
(23000, 500)


In [180]:
compressed_masks[:4]

[array([6095, 6096, 6097, 6098, 6099, 6100]),
 array([6095, 6096, 6097, 6098, 6099, 6100, 6101]),
 array([6095, 6096, 6097, 6098, 6099, 6100, 6101, 6102]),
 array([6095, 6096, 6097, 6098, 6099, 6100, 6101, 6102, 6103])]

In [182]:
snps_masks_lists[:4]

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  15